pipeline:  # night_horizons.pipeline.MetadataProcessor
  stage: metadata_processor
  score_output: false
  verbose: true
io_manager:  # night_horizons.io_manager.IOManager
  root_dir:
  file_exists: overwrite
  tracked_file_key:
  checkpoint_subdir: checkpoints
  checkpoint_selection:
  checkpoint_tag: _i{:06d}
  checkpoint_freq: 100
  data_ios: {}
  input_dir: /data/input
  input_description:
    img_log: metadata/220513-FH135/image.log
    imu_log: metadata/220513-FH135/PresIMULog.csv
    gps_log: metadata/220513-FH135/GPSLog.csv
    images:
      directory: images/220513-FH135/23085687
      pattern: \.(raw|tif|tiff)$
  output_dir: ./test/test_data/temp
  output_description:
    metadata: 220513-FH135-metadata.csv
    used_config: used-config.yaml
crs:  # pyproj.crs.crs.CRS
  projparams: EPSG:3857
random_state: # sklearn.utils.validation.check_random_state
  seed: 159234
metadata_processor:
  version: fh135_metadata_processor
