pipeline:  # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.pipeline.html#night_horizons.pipeline.MetadataProcessor
  stage: metadata_processor
  score_output: false
  verbose: true
io_manager:  # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.io_manager.html#night_horizons.io_manager.IOManager
  root_dir:
  file_exists: overwrite
  checkpoint_file_key:
  checkpoint_subdir: checkpoints
  checkpoint_selection:
  checkpoint_tag: _i{:06d}
  checkpoint_freq: 100
  input_dir: /data/input
  input_description:
    img_log: nitelite.metadata/220513-FH135/image.log
    imu_log: nitelite.metadata/220513-FH135/PresIMULog.csv
    gps_log: nitelite.metadata/220513-FH135/GPSLog.csv
    images:
      directory: nitelite.images/220513-FH135
      pattern: \.(raw|tif|tiff)$
  output_dir: ./test/test_data/temp
  output_description:
    metadata: combined_metadata.csv
    used_config: used-config.yaml
crs:  # pyproj.crs.crs.CRS
  projparams: EPSG:3857
random_state: # sklearn.utils.validation.check_random_state
  seed: 159234
metadata_processor:
  version: fh135_metadata_processor
fh135_metadata_processor:  # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.transformers.preprocessors.html#night_horizons.transformers.preprocessors.MetadataPreprocessor135
  output_columns:
  use_cached_output: true
  unhandled_files: drop
  tz_offset_in_hr: 5.0
  passthrough: &id001 []
fh145_metadata_processor:  # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.transformers.preprocessors.html#night_horizons.transformers.preprocessors.MetadataPreprocessor145
  output_columns:
  use_cached_output: true
  unhandled_files: drop
  tz_offset_in_hr: 5.0
  passthrough: *id001
