pipeline:  # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.pipeline.html#night_horizons.pipeline.MosaicMaker
  stage: mosaicker
  score_output: false
  verbose: true
io_manager:  # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.io_manager.html#night_horizons.io_manager.MosaicIOManager
  output_description:
    mosaic: mosaic.tiff
    settings: settings.yaml
    log: log.csv
    used_config: used-config.yaml
  root_dir:
  file_exists: new
  tracked_file_key: mosaic
  checkpoint_subdir: checkpoints
  checkpoint_selection:
  - mosaic
  - settings
  - log
  checkpoint_tag: _i{:06d}
  checkpoint_freq: 100
  input_dir: /data/input
  input_description:
    referenced_images:
      directory: nitelite.referenced-images/220513-FH135
      pattern: Geo\s\d+_1\.(tif|tiff)$
  output_dir: ./test/test_data/temp
crs:  # pyproj.crs.crs.CRS
  projparams: EPSG:3857
random_state: # sklearn.utils.validation.check_random_state
  seed: 15923
metadata_processor:
  version: fh135_metadata_processor
fh135_metadata_processor:  # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.transformers.preprocessors.html#night_horizons.transformers.preprocessors.MetadataPreprocessor135
  output_columns:
  use_cached_output: true
  unhandled_files: drop
  tz_offset_in_hr: 5.0
  passthrough: &id001 []
fh145_metadata_processor:  # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.transformers.preprocessors.html#night_horizons.transformers.preprocessors.MetadataPreprocessor145
  output_columns:
  use_cached_output: true
  unhandled_files: drop
  tz_offset_in_hr: 5.0
  passthrough: *id001
geotiff_preprocessor:  # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.transformers.preprocessors.html#night_horizons.transformers.preprocessors.GeoTIFFPreprocessor
  spatial_error: 0.0
  padding_fraction: 0.1
  passthrough: true
mosaicker:  # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.image_processing.mosaicking.html#night_horizons.image_processing.mosaicking.Mosaicker
  pixel_width:
  pixel_height:
  dtype: uint8
  fill_value:
  n_bands: 4
  log_keys:
  - ind
  - return_code
  passthrough: true
processor: # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.image_processing.processors.html#night_horizons.image_processing.processors.DatasetUpdater
  log_keys: &id002 []
  save_return_codes: &id003 []
  use_safe_process: true
  dtype: uint8
scorer: # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.image_processing.scorers.html#night_horizons.image_processing.scorers.DatasetScorer
  log_keys: *id002
  save_return_codes: *id003
  use_safe_process: true
  dtype: uint8
image_operator:  # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.image_processing.operators.html#night_horizons.image_processing.operators.ImageBlender
  fill_value:
  outline: 0
  log_keys: []
image_scorer:  # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.image_processing.scorers.html#night_horizons.image_processing.scorers.SimilarityScoreOperator
  allow_resize: true
  compare_nonzero: true
  tm_metric: 5
  log_keys: []
  acceptance_threshold: 0.99
