pipeline:  # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.pipeline.html#night_horizons.pipeline.QueryProcessor
  stage: query_processor
  score_output: false
  verbose: true
io_manager:  # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.io_manager.html#night_horizons.io_manager.IOManager
  root_dir:
  file_exists: overwrite
  checkpoint_file_key:
  checkpoint_subdir: checkpoints
  checkpoint_selection:
  checkpoint_tag: _i{:06d}
  checkpoint_freq: 100
  input_dir: /data/input
  input_description:
    metadata: nitelite.pipeline-output/sequential-mosaic/REPLACE_THIS/y_pred.csv
    referenced_images:
      directory: nitelite.pipeline-output/sequential-mosaic/REPLACE_THIS/referenced_images
  output_dir: ./test/test_data/temp
  output_description:
    metadata_selected: y_pred_selected.csv
    used_config: used-config.yaml
crs:  # pyproj.crs.crs.CRS
  projparams: EPSG:3857
random_state: # sklearn.utils.validation.check_random_state
  seed: 159234
metadata_processor:  # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.transformers.preprocessors.html#night_horizons.transformers.preprocessors.MetadataPreprocessor
  output_columns:
  use_cached_output: true
  unhandled_files: drop
  tz_offset_in_hr: 5.0
  passthrough: []
query_processor: # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.transformers.filters.html#night_horizons.transformers.filters.QueryFilter
  condition: >-
    (mAltitude > 13000.) &(imuGyroMag < 0.075)
