pipeline:  # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.pipeline.html#night_horizons.pipeline.SequentialMosaicMaker
  stage: sequential_mosaicker
  score_output: true
  verbose: true
io_manager:  # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.io_manager.html#night_horizons.io_manager.SequentialMosaicIOManager
  output_description:
    mosaic: mosaic.tiff
    settings: settings.yaml
    log: log.csv
    y_pred: y_pred.csv
    progress_images_dir: progress_images
    referenced_images: referenced_images/img_ind{:06d}.tiff
    used_config: used-config.yaml
  checkpoint_selection:
  - mosaic
  - settings
  - log
  - y_pred
  input_dir: /data/input
  input_description:
    img_log: nitelite.metadata/220513-FH135/image.log
    imu_log: nitelite.metadata/220513-FH135/PresIMULog.csv
    gps_log: nitelite.metadata/220513-FH135/GPSLog.csv
    images:
      directory: nitelite.images/220513-FH135
      pattern: \.(raw|tif|tiff)$
    referenced_images:
      directory: nitelite.referenced-images/220513-FH135
      pattern: Geo\s\d+_1\.(tif|tiff)$
    test_referenced_images:
      directory: test_referenced_images/220513-FH135
  output_dir: ./test/test_data/temp
  checkpoint_freq: 1
crs:  # pyproj.crs.crs.CRS
  projparams: EPSG:3857
random_state: # sklearn.utils.validation.check_random_state
  seed: 1592
metadata_processor:  # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.transformers.preprocessors.html#night_horizons.transformers.preprocessors.MetadataPreprocessor
  output_columns:
  use_cached_output: true
  unhandled_files: drop
  tz_offset_in_hr: 5.0
  passthrough: []
data_splitter:  # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.io_manager.html#night_horizons.io_manager.ReferencedRawSplitter
  test_size: 0.2
  max_raw_size:
  drop_raw_images: false
  random_state:
  use_test_dir: true
metadata_image_registrar:  # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.image_processing.registration.html#night_horizons.image_processing.registration.MetadataImageRegistrar
  passthrough: false
  use_observed_error: true
  camera_angles:
    0: 30.0
    1: 0.0
    2: 30.0
  angle_error: 5.0
  padding_fraction: 1.5
geotiff_preprocessor:  # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.transformers.preprocessors.html#night_horizons.transformers.preprocessors.GeoTIFFPreprocessor
  spatial_error: 0.0
  padding_fraction: 0.1
  passthrough: true
altitude_filter:  # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.transformers.filters.html#night_horizons.transformers.filters.AltitudeFilter
  column: mAltitude
  float_altitude: 100.0
steady_filter: # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.transformers.filters.html#night_horizons.transformers.filters.SteadyFilter
  column: imuGyroMag
  max_gyro: 0.075
order:  # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.transformers.order.html#night_horizons.transformers.order.SensorAndDistanceOrder
  apply: true
  sensor_order_col: camera_num
  sensor_order_map:
    0: 1
    1: 0
    2: 2
  coords_cols:
  - x_center
  - y_center
preprocessor_pipeline: # sklearn.pipeline.Pipeline
  memory:
  verbose: false
mosaicker:  # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.image_processing.mosaicking.html#night_horizons.image_processing.mosaicking.SequentialMosaicker
  memory_snapshot_freq: 10
  pixel_width:
  pixel_height:
  fill_value:
  dtype: uint8
  n_bands: 4
  passthrough: true
  log_keys:
  - i
  - ind
  - return_code
  - abs_det_M
processor: # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.image_processing.processors.html#night_horizons.image_processing.processors.ReferencerDatasetUpdater
  log_keys: &id001 []
  save_return_codes:
  - bad_det
  - out_of_bounds
  use_safe_process: true
  dtype: uint8
scorer: # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.image_processing.scorers.html#night_horizons.image_processing.scorers.ReferencedImageScorer
  crs:
image_operator:  # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.image_processing.operators.html#night_horizons.image_processing.operators.ImageAlignerBlender
  det_min: 0.6
  det_max: 1.7
  required_brightness: 0.03
  required_bright_pixel_area: 50000
  n_matches_used: 500
  find_homography_options:
    method: 8
    ransacReprojThreshold: 5.0
  fill_value:
  outline: 0
  log_keys:
  - abs_det_M
  - duration
preprocessor_train: # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.transformers.preprocessors.html#night_horizons.transformers.preprocessors.GeoTIFFPreprocessor
  spatial_error: 0.0
  padding_fraction: 0.1
  passthrough: true
io_manager_train:  # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.io_manager.html#night_horizons.io_manager.TrainMosaicIOManager
  output_description:
    mosaic: mosaic.tiff
    settings: settings_train.yaml
    log: log_train.yaml
    y_pred: y_pred_train.csv
    progress_images_dir_train: progress_images_train
    used_config: used-config.yaml
  file_exists: pass
  input_dir: /data/input
  input_description:
    img_log: nitelite.metadata/220513-FH135/image.log
    imu_log: nitelite.metadata/220513-FH135/PresIMULog.csv
    gps_log: nitelite.metadata/220513-FH135/GPSLog.csv
    images:
      directory: nitelite.images/220513-FH135
      pattern: \.(raw|tif|tiff)$
    referenced_images:
      directory: nitelite.referenced-images/220513-FH135
      pattern: Geo\s\d+_1\.(tif|tiff)$
    test_referenced_images:
      directory: test_referenced_images/220513-FH135
  output_dir: ./test/test_data/temp
  checkpoint_freq: 1
image_operator_train:  # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.image_processing.operators.html#night_horizons.image_processing.operators.ImageBlender
  fill_value:
  outline: 0
  log_keys: []
processor_train: # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.image_processing.processors.html#night_horizons.image_processing.processors.DatasetUpdater
  log_keys: *id001
  save_return_codes: []
  use_safe_process: true
  dtype: uint8
mosaicker_train:  # https://adlerfarhorizons.github.io/night-horizons-mapmaker/build/html/night_horizons.image_processing.mosaicking.html#night_horizons.image_processing.mosaicking.Mosaicker
  pixel_width:
  pixel_height:
  dtype: uint8
  fill_value:
  n_bands: 4
  log_keys:
  - ind
  - return_code
  passthrough: true
