services:
  night-horizons:
    image: night-horizons
    restart: always
    environment: 
      POSTGRES_DB: gis
      POSTGRES_USER: gis
      POSTGRES_PASSWORD: gis
    ports:
      - 5432:5432
    volumes:
      - ./data/postgis:/var/lib/postgresql/data