###############################################################################
# Example Configuration File
###############################################################################

# I/O settings
io_manager:
  input_dir: /data/220513-FH135
  input_description:
    raw_images:
      directory: nitelite.images/raw
      extension: ['raw', 'tif', 'tiff']
    referenced_images:
      directory: nitelite.images/referenced
      extension: ['tif', 'tiff']
      pattern: 'Geo\s\d+_1.tif'
  output_dir: /data/220513-FH135/mosaics/sequential
  file_exists: new

data_splitter:
  test_size: 10

# Coordinate reference-system employed
crs:
  projparams: 'EPSG:3857'

random_state: 
  seed: 159234