###############################################################################
# Example Configuration File
###############################################################################

io_manager:
  input_dir: ./test/test_data
  input_description:
    raw_images:
      directory: images
      extension: ['raw', 'tif', 'tiff']
    referenced_images:
      directory: referenced_images
      extension: ['tif', 'tiff']
      pattern: 'Geo\s\d+_\d.tif'

global:
  # Coordinate reference-system employed
  crs: 'EPSG:3857'
  latlon_crs: 'EPSG:4326'

# Aesthetics
color_palette: deep
