###############################################################################
# Example Configuration File
###############################################################################

mosaic_type: simple

io_manager:
  input_dir: /data/220513-FH135
  input_description:
    raw_images:
      directory: images/raw
      extension: ['raw', 'tif', 'tiff']
    referenced_images:
      directory: images/referenced
      extension: ['tif', 'tiff']
      pattern: 'Geo\s\d+_\d.tif'
  output_dir: /data/220513-FH135/mosaics/referenced
  file_exists: new

global:
  # Coordinate reference-system employed
  crs: 'EPSG:3857'
  latlon_crs: 'EPSG:4326'

# Aesthetics
color_palette: deep
